var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(auth)/auth/login/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__1lhi36j._.js")
R.c("server/chunks/ssr/node_modules_next_dist_1n3w9lb._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0p2-9mm._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0j26pto._.js")
R.c("server/chunks/ssr/app_layout_tsx_2144vk_._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0q-w892.js")
R.c("server/chunks/ssr/app_(auth)_layout_tsx_1vfqhb4._.js")
R.c("server/chunks/ssr/_next-internal_server_app_(auth)_auth_login_page_actions_05lo-rn.js")
R.m(50479)
module.exports=R.m(50479).exports
