var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(dashboard)/skills/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__04jkt2l._.js")
R.c("server/chunks/ssr/node_modules_next_dist_1n3w9lb._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0p2-9mm._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0j26pto._.js")
R.c("server/chunks/ssr/app_layout_tsx_2144vk_._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0q-w892.js")
R.c("server/chunks/ssr/_1myushu._.js")
R.c("server/chunks/ssr/_next-internal_server_app_(dashboard)_skills_page_actions_1orngl-.js")
R.m(53806)
module.exports=R.m(53806).exports
